server:
  port: 4242
#  ssl:
#    enabled: true
#    key-store: classpath:xmash.p12
#    key-store-password: qwe123
#    key-store-type: PKCS12
#    key-alias: xmash

springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'

spring:
  application:
    name: xmash
  datasource:
    url: jdbc:mysql://${DB_IP_PORT}/xmash?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화
cors:
  allowed-origins: ${ALLOWED_ORIGINS}  # 환경 변수로부터 허용할 출처 읽기