server:
  port: 4243

spring:
  application:
    name: xmash
  datasource:
    url: ${DB_IP_PORT}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화.


springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    display-request-duration: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}  # 환경 변수로부터 암호화 키 읽기