spring:
  application:
    name: xmash
  datasource:
    url: ENC(UjQMa2lNzIAPXTwAhmYz2EI6Z2Ko8CxXvbC34JwjxLWQmMR2FdJQrBH6tG6Iiv43spc58g8qedobYixvoFbR+/Jac7ZZNe2sxpHPjDMILwCtAR7CoCA4GQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(+cOLpHmDCnRjwd/h8yrTJQ==)
    password: ENC(vaBzipJGlEx7697EnnmFJTtfDSVZhBrS)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화.

springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    display-request-duration: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: very!hard@pw