spring:
  application:
    name: xmash
  datasource:
    url: ENC(XTinqhNkg90Vj3zg4eh+qE9epKjcKkGfhwFYV//vU2Lfbmksg0NVaa1QgXW0O/dX0a0PYruXWDTd7BodnnuZ7IkvaDr7NVjFYm8eh4vHlt2MLxx72dkF/Q==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(+cOLpHmDCnRjwd/h8yrTJQ==)
    password: ENC(N82lmEig2NTYBKRNi+8Q4dz8z+vqOE6f)
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화.


springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    display-request-duration: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}  # 환경 변수로부터 암호화 키 읽기