spring:
  application:
    name: xmash
  datasource:
    url: jdbc:mysql://${DB_IP_PORT}/xmash?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화.


springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    display-request-duration: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}  # 환경 변수로부터 암호화 키 읽기

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}