FROM --platform= azul/zulu-openjdk:21

ARG JARFILE=build/libs/*.jar

COPY ${JARFILE} ./app.jar

CMD ["java", "-jar", "./app.jar", "--spring.profiles.active=prod", "--spring.output.ansi.enabled=always"]
