FROM --platform= azul/zulu-openjdk:21

RUN mkdir webapp

ARG JARFILE=build/libs/*.jar

COPY ${JARFILE} ./webapp/app.jar

CMD ["java", "-jar", "./waebapp/app.jar", "--spring.profiles.active=dev", "--spring.output.ansi.enabled=always"]
