FROM --platform=linux/arm64 azul/zulu-openjdk-alpine:21-jdk

ARG JARFILE=build/libs/*.jar

COPY ${JARFILE} /app.jar

CMD ["java", "-jar", "/app.jar", "--spring.profiles.active=dev", "--spring.output.ansi.enabled=always"]
