name: BE DEV CI/CD Pipeline

on:
  push:
    branches:
      - be/dev
      - be/ci/118
    paths:
      - 'be/**'
      - '*'

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./be/xmash

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./be/xmash

      - name: Build Docker image
        working-directory: ./be/xmash
        run: |
          ls -la
          echo "----------------------------"
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev ./

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev

  deploy:
    needs: build
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          # Create the .ssh directory
          mkdir -p ~/.ssh
          
          # Add the private key
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add the known_hosts file to avoid SSH host key verification
          ssh-keyscan -p ${{ secrets.GCP_SSH_PORT }} ${{ secrets.GCP_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Transfer files
        run: |
          scp -P ${{ secrets.GCP_SSH_PORT }} -r be/xmash/build/libs/xmash-0.0.1-SNAPSHOT.jar ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_PUBLIC_IP }}:/home/sejin/xmash

      - name: Deploy to server
        run: |
          ssh -tt ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_PUBLIC_IP }} -p ${{ secrets.GCP_SSH_PORT }} << 'EOF'
          source .bashrc
          # Stop the running application if any
          pkill -f 'java -jar /home/sejin/xmash/xmash-0.0.1-SNAPSHOT.jar'
          
          nohup java -jar /home/sejin/xmash/xmash-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev > /home/sejin/xmash/logs/xmash.log 2>&1 & disown
          
          # Remove the old jar file
          echo "Deployment completed successfully!"
          exit
          EOF
    
