name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: be

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./be

      - name: Run backend tests
        run: mvn test
        working-directory: ./be

#  build-frontend: 만들꺼면 쓰시오
#    name: Build Frontend
#    runs-on: ubuntu-latest
#    needs: build-backend
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          path: fe

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs : [build-backend]
#    needs: [build-backend, build-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          # Your deployment commands here
          echo "Deploying application"