name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 1
    paths:
      - 'be/**'
  pull_request:
    branches:
      - main
    paths:
      - 'be/**'

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '21'
#
#      - name: Cache Gradle packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#        working-directory: be/xmash
#
#      - name: Build with Gradle
#        run: ./gradlew build
#        working-directory: be/xmash
#
#      - name: Run backend tests
#        run: ./gradlew test
#        working-directory: be/xmash

#  build-frontend: 만들꺼면 쓰시오
#    name: Build Frontend
#    runs-on: ubuntu-latest
#    needs: build-backend
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          path: fe

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs : [build-backend]
#    needs: [build-backend, build-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          # Create the .ssh directory
          mkdir -p ~/.ssh

          # Add the private key
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the known_hosts file to avoid SSH host key verification
          ssh-keyscan -p ${{ secrets.GCP_SSH_PORT }} ${{ secrets.GCP_PUBLIC_IP }} >> ~/.ssh/known_hosts
 
          
      - name: Test SSH Connection and Output Hostname
        run: |
          ssh ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_PUBLIC_IP }} -p ${{ secrets.GCP_SSH_PORT }} 'hostname'

      - name: Deploy to server
        run: |
          ssh ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_PUBLIC_IP }} -p ${{ secrets.GCP_SSH_PORT }} << 'EOF'
          # Your deployment commands here
          echo "Deploying application"
          EOF